{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dianyaai.asr",
    "module": "dianyaai-asr-android-sdk",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "dianyaai-asr-android-sdk-0.0.6.aar",
          "url": "dianyaai-asr-android-sdk-0.0.6.aar",
          "size": 1003,
          "sha512": "0c6e97bb1481a600cae83ad724acd52b1c20683bd3e7364891a21a22fa0e988b247026be007f6a39cacfa436dd4c73a60c3d70472e9eed4df3cb078c4a311591",
          "sha256": "5338d58437ab5f6999ab727f78a82ac369ce858ddbe0f424db14e603e3423538",
          "sha1": "7523f6fa290c85fc774190ca92761df8bcd1934f",
          "md5": "b42c990a9d40ea5ad9de9af628764f1e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "dianyaai-asr-android-sdk-0.0.6.aar",
          "url": "dianyaai-asr-android-sdk-0.0.6.aar",
          "size": 1003,
          "sha512": "0c6e97bb1481a600cae83ad724acd52b1c20683bd3e7364891a21a22fa0e988b247026be007f6a39cacfa436dd4c73a60c3d70472e9eed4df3cb078c4a311591",
          "sha256": "5338d58437ab5f6999ab727f78a82ac369ce858ddbe0f424db14e603e3423538",
          "sha1": "7523f6fa290c85fc774190ca92761df8bcd1934f",
          "md5": "b42c990a9d40ea5ad9de9af628764f1e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dianyaai-asr-android-sdk-0.0.6-javadoc.jar",
          "url": "dianyaai-asr-android-sdk-0.0.6-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
